package org.offitec.osp.domain.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "project_details")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class ProjectDetails {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "project_details_seq_gen")
    @SequenceGenerator(name = "project_details_seq_gen", sequenceName = "osp_project_details_sequence", allocationSize = 50)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "project_id", nullable = false)
    private Project project;

    // ManyToOne (not OneToOne): the same unit can appear in many projects, and a
    // project can hold many units. A OneToOne here forces a UNIQUE constraint on
    // product_id, which breaks adding the same unit to more than one project.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id", nullable = false)
    private Unit unit;

    // One row per operating mode: a heat pump holds a COOLING and a HEATING row (both rendered
    // into the single dual-mode PDF on this detail); a chiller holds a single COOLING row. The FK
    // lives on the child table (project_details_id), so this detail owns the collection.
    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @JoinColumn(name = "project_details_id")
    private List<CustomCalculationValues> customCalculationValues = new ArrayList<>();

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    @JoinColumn(name = "project_details_id")
    private List<CalculationOutputValues> calculationOutputValues = new ArrayList<>();

    // Language the stored report PDF was rendered in ("en"/"de"). Remembered so the
    // report regenerates in the same language when the project's info changes.
    @Column(name = "language")
    private String language;

    private String pdfUrl;

    // Snapshot of the rendered report (serialized UnitReportModel) taken when the unit is added to the
    // project. On a project-info edit the report is regenerated by overlaying only the project block onto
    // this snapshot — no engine recalculation — so the computed values never drift. Null for rows created
    // before snapshots existed (those fall back to recompute on the next regeneration).
    @Column(name = "report_model_json", columnDefinition = "text")
    private String reportModelJson;
}
